##
# MariaDB - tasks
---

- name: Install MariaDB server and client packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - mariadb-server
    - mariadb-client
    - python-mysqldb

- name: Configure MariaDB server
  template:
    src: 50-server.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql
