##
# Jenkins - job tasks
---

- name: Check Jenkins job
  jenkins_api:
    jenkins_url: "http://{{ ansible_fqdn }}:8080"
    command: job_exists
    args:
      - "{{ site.name }}"
  register: job

- debug:
    var: job

- name: Create Jenkins job
  jenkins_api:
    jenkins_url: "http://{{ ansible_fqdn }}:8080"
    command: create_node
    args:
      - "{{ site.name }}"
      - "{{ lookup('template', 'build.xml.j2') }}"
  when: not job.job_exists

- name: Check Jenkins job promotion
  jenkins_api:
    jenkins_url: "http://{{ ansible_fqdn }}:8080"
    command: promotion_exists
    args:
      - deploy
      - "{{ site.name }}"
  register: promotion

- debug:
    var: promotion

- name: Create Jenkins job promotion
  jenkins_api:
    jenkins_url: "http://{{ ansible_fqdn }}:8080"
    command: create_promotion
    args:
      - deploy
      - "{{ site.name }}"
      - "{{ lookup('template', 'deploy.xml.j2') }}"
  when: not promotion.promotion_exists
