##
# Jenkins - job tasks
---

- name: Create Jenkins Drupal autoupdate job directory
  file:
    path: "/var/lib/jenkins/jobs/{{ site.name }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775

- name: Create Jenkins Drupal autoupdate job configuration
  template:
    src: build.xml.j2
    dest: "/var/lib/jenkins/jobs/{{ site.name }}/config.xml"
    owner: jenkins
    group: jenkins
    mode: 0664
  notify: restart jenkins

- name: Create Jenkins Drupal autoupdate promotions directory
  file:
    path: "/var/lib/jenkins/jobs/{{ site.name }}/promotions/deploy"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775

- name: Create Jenkins Drupal autoupdate promotions job configuration
  template:
    src: deploy.xml.j2
    dest: "/var/lib/jenkins/jobs/{{ site.name }}/promotions/deploy/config.xml"
    owner: jenkins
    group: jenkins
    mode: 0664
  notify: restart jenkins
