##
# Apache2 - tasks
---

- name: Install Apache2
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - apache2
    - apache2-utils
    - libapache2-mod-php7.2

- name: Enable modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - rewrite
  notify: restart apache2
